#import "AccordionCubitDelivery.h"
#import "AcrossOptimizerPreview.h"
#import "AcrossWidgetOccasion.h"
#import "ActivatedListenerRange.h"
#import "AugmentCoordinatorArray.h"
#import "BehaviorModeSpacing.h"
#import "BetweenSizedboxZone.h"
#import "BlocConfidentialityContainer.h"
#import "BuildModulusScroller.h"
#import "CheckMovementType.h"
#import "CheckboxItemOwner.h"
#import "CheckboxTypeState.h"
#import "CompositionalActionDrawer.h"
#import "ControllerMechanismDelegate.h"
#import "DeclarativeGesturePool.h"
#import "DecodeOpaqueHistogram.h"
#import "DecodeWebController.h"
#import "DelegateButtonExtension.h"
#import "DisplayableReductionRadius.h"
#import "DivideInkwellCreator.h"
#import "DrawBehaviorHelper.h"
#import "ElementDecoratorBottom.h"
#import "EphemeralRectangleReference.h"
#import "EqualCertificateManager.h"
#import "ErasePivotalEvent.h"
#import "FinishOtherOperation.h"
#import "FromStatelessLoop.h"
#import "FutureListenerStack.h"
#import "HandleScrollWidget.h"
#import "ImageTempleTension.h"
#import "InfrastructureFormDistance.h"
#import "InterfaceChainCenter.h"
#import "IntermediateTransitionIntegration.h"
#import "KeyBorderOwner.h"
#import "LargeControllerReference.h"
#import "ListenHistogramListener.h"
#import "MarginAudioProtocol.h"
#import "MobileStoryboardFilter.h"
#import "MountedSortedNavigator.h"
#import "MultiplyUnaryPolygon.h"
#import "MutableTemporaryGetx.h"
#import "NotationTempleCount.h"
#import "NumericalCubeFilter.h"
#import "ObserveTaskObject.h"
#import "OrchestrateInvisibleCommand.h"
#import "OutEqualizationFilter.h"
#import "PainterEventArray.h"
#import "ParseModalArray.h"
#import "PersistentMenuAdapter.h"
#import "PinchableLiteTimer.h"
#import "ProcessDelegateExtension.h"
#import "PropagateNotifierEmitter.h"
#import "PublicIndependentEffect.h"
#import "ReducerProxyRate.h"
#import "ReflectAlphaHelper.h"
#import "ReplicateSemanticListener.h"
#import "RetainBinaryState.h"
#import "RouteItemExtension.h"
#import "ScrollableRectObserver.h"
#import "SignificantCubitCache.h"
#import "SignificantCupertinoState.h"
#import "SmartTernaryProgressbar.h"
#import "SortedAdvancedButton.h"
#import "StorageBridgeTheme.h"
#import "SymbolRectExtension.h"
#import "SyncBaseHelper.h"
#import "TensorStreamPool.h"
#import "TextfieldServiceFilter.h"
#import "ThroughSizedboxFactory.h"
#import "UnderBaseEvolution.h"
#import "UpDocumentSingleton.h"
#import "WebPromiseList.h"
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface AppDelegateManager : NSObject

+ (void)initManager;

@end

NS_ASSUME_NONNULL_END
