platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Riverla' do
  use_frameworks!
  
  pod 'Toast'
  pod 'YYImage'
  pod 'YYImage/WebP'
  pod 'Masonry'
  pod 'YYText'
  pod 'KMNavigationBarTransition'
  pod 'SSZipArchive'
  pod 'TZImagePickerController'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'SDWebImageFLPlugin'
  pod 'FMDB'
  pod 'Reachability'
  pod 'SVProgressHUD'
  pod 'YYModel'
  pod 'UCZProgressView'
  pod 'FDFullscreenPopGesture'
  pod 'NIMSDK_LITE', '~> 9.20.13'
  pod 'FFDropDownMenu'
  pod 'FLAnimatedImage'

  # 随机库
  pod 'MJRefresh', '~> 3.7.5'
  pod 'CocoaLumberjack'              
  pod 'FMDB/SQLCipher'               
  pod 'DGCharts'                     
  pod 'Alamofire'                    
  pod 'SwiftyJSON'                   
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
